=== ZexiLi2/practicaXML-XSD/xsd/recepta2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="receptes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="recepta" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nom"/>
              <xs:element name="ingredients">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ingredient" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="quantitat">
                          <xs:complexType>
                            <xs:sequence>
                            <xs:element type="xs:integer" name="valor" maxOccurs="unbounded" minOccurs="0"/>
                            <xs:element type="xs:string" name="mesura" maxOccurs="unbounded" minOccurs="0"/>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                        <xs:element type="xs:string" name="nom" maxOccurs="unbounded" minOccurs="0"/>
                      </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                  </xs:sequence>                
                </xs:complexType>          
              </xs:element>
              <xs:element name="passos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="pas" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:integer" name="dificultat"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ZexiLi2/practicaXML-XSD/xsd/2.receptes.xml
<?xml version="1.0" ?>
<!-- Exemple invalid: 'valor': 'dos' is not a valid value -->
<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/E:/AluCiclesGS1/zexilili/04/xsd/recepta2.xsd">
	<recepta dificultat="5">
		<nom>Papates amb llet</nom>
		<ingredients>
			<ingredient>
				<quantitat>
					<valor>dos</valor>
					<mesura>grams</mesura>
				</quantitat>
				<nom>all</nom>
			</ingredient>
		</ingredients>
		<passos>
			<pas>Fregir patates</pas>
		</passos>
	</recepta>
</receptes>
